#!/usr/bin/env python3
"""Emit a two-target macOS Xcode project (app + WidgetKit extension)."""
import os, itertools, re, subprocess, sys

APP_ID = "com.phonpreecha.vibewidget"
WID_ID = APP_ID + ".usagewidget"
DEPLOY = "14.0"


def detect_team():
    """The Team ID that signs this build.

    macOS requires the App Group to carry the signer's Team ID as a prefix, so
    this cannot be a constant: every machine builds with its own certificate.
    The Team ID is the certificate's OU, not the ID shown in its common name.
    """
    override = os.environ.get("VIBEWIDGET_TEAM")
    if override:
        return override

    try:
        pem = subprocess.run(
            ["security", "find-certificate", "-c", "Apple Development", "-p"],
            capture_output=True, text=True, check=True).stdout
        subject = subprocess.run(
            ["openssl", "x509", "-noout", "-subject"],
            input=pem, capture_output=True, text=True, check=True).stdout
    except (subprocess.CalledProcessError, FileNotFoundError):
        subject = ""

    match = re.search(r"OU\s*=\s*([A-Z0-9]+)", subject)
    if match:
        return match.group(1)

    sys.exit(
        "no 'Apple Development' certificate in the login keychain.\n"
        "\n"
        "  Open Xcode > Settings > Accounts, add your Apple ID (a free one is\n"
        "  enough), then Manage Certificates... > + > Apple Development.\n"
        "\n"
        "  Already have one under a different name? Pass it directly:\n"
        "      VIBEWIDGET_TEAM=XXXXXXXXXX ./build.sh"
    )


def detect_version():
    """Marketing version: an explicit override, else the current git tag."""
    override = os.environ.get("VIBEWIDGET_VERSION")
    if override:
        return override.lstrip("v")
    try:
        tag = subprocess.run(["git", "describe", "--tags", "--abbrev=0"],
                             capture_output=True, text=True, check=True).stdout
        return tag.strip().lstrip("v") or "0.0.0"
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "0.0.0"


# Homebrew forks its build with setsid(2), which drops the process out of the
# user's security session: no login keychain, so no identity to sign with and
# no certificate to read a Team ID from. That build is left ad-hoc signed and
# Tools/refresh.sh signs it for real afterwards, from the user's own shell.
UNSIGNED = os.environ.get("VIBEWIDGET_UNSIGNED") == "1"

TEAM = "" if UNSIGNED else detect_team()
VERSION = detect_version()
BUILD = os.environ.get("VIBEWIDGET_BUILD", "1")

# Both targets read this back out of their own Info.plist at runtime, so the
# group identifier is written in exactly one place: here. An unsigned build
# carries a placeholder that refresh.sh overwrites — seeing it in an installed
# bundle means that step never ran.
APP_GROUP = "%s.group.com.phonpreecha.vibewidget" % (TEAM or "UNSIGNED")

_ids = itertools.count(1)
def uid():
    return "AA%022X" % next(_ids)

SHARED = ["UsageModels.swift", "ClaudeUsageProvider.swift", "CodexUsageProvider.swift",
          "UsageStore.swift", "UsageViews.swift", "AppSettings.swift",
          "VibeWidgetURL.swift",
          "SelectProviderIntent.swift"]
APP_SRC = ["VibeWidgetApp.swift", "DashboardView.swift", "SettingsView.swift",
           "MenuBarGauge.swift", "MenuBarPanel.swift", "UpdateChecker.swift"]
WID_SRC = ["UsageWidget.swift", "ProviderWidget.swift"]
ASSETS = ["claude.png", "chatgpt.png"]
APP_ASSETS = ["navicon.png"]

# --- file references -------------------------------------------------------
refs = {}   # path -> (id, name, filetype, sourcetree)
def fref(path, ftype="sourcecode.swift", tree="\"<group>\""):
    refs[path] = (uid(), os.path.basename(path), ftype, tree)
    return refs[path][0]

for f in SHARED: fref("Shared/" + f)
for f in APP_SRC: fref("App/" + f)
for f in WID_SRC: fref("Widget/" + f)
fref("App/Info.plist", "text.plist.xml")
fref("Widget/Info.plist", "text.plist.xml")
# Generated by Tools/MakeIcon.swift; see build.sh.
fref("App/AppIcon.icns", "image.icns")
# Provider logos. Both targets need their own copy: the widget extension is a
# separate bundle and cannot reach the app's resources.
for f in ASSETS + APP_ASSETS: fref("Assets/" + f, "image.png")

APP_PROD = uid(); WID_PROD = uid()

# --- build files -----------------------------------------------------------
buildfiles = []   # (buildfile_id, fileref_id, comment)
def bf(path):
    b = uid(); buildfiles.append((b, refs[path][0], refs[path][1])); return b

app_sources = [bf("Shared/" + f) for f in SHARED] + [bf("App/" + f) for f in APP_SRC]
wid_sources = [bf("Shared/" + f) for f in SHARED] + [bf("Widget/" + f) for f in WID_SRC]
app_resources = ([bf("App/AppIcon.icns")]
                 + [bf("Assets/" + f) for f in ASSETS + APP_ASSETS])
wid_resources = [bf("Assets/" + f) for f in ASSETS]

EMBED_BF = uid()   # widget product embedded into the app

# --- ids -------------------------------------------------------------------
PROJ, MAIN_GROUP, PROD_GROUP = uid(), uid(), uid()
G_SHARED, G_APP, G_WID, G_ASSETS = uid(), uid(), uid(), uid()
APP_TGT, WID_TGT = uid(), uid()
APP_SRC_PH, APP_FRM_PH, APP_RES_PH, APP_EMB_PH = uid(), uid(), uid(), uid()
WID_SRC_PH, WID_FRM_PH, WID_RES_PH = uid(), uid(), uid()
DEP, PROXY = uid(), uid()
CL_PROJ, CL_APP, CL_WID = uid(), uid(), uid()
BC = {k: uid() for k in ("pd", "pr", "ad", "ar", "wd", "wr")}

out = []
w = out.append
w("// !$*UTF8*$!\n{\n\tarchiveVersion = 1;\n\tclasses = {\n\t};\n\tobjectVersion = 56;\n\tobjects = {\n")

w("\n/* Begin PBXBuildFile section */\n")
for b, f, name in buildfiles:
    w("\t\t%s /* %s in Sources */ = {isa = PBXBuildFile; fileRef = %s /* %s */; };\n" % (b, name, f, name))
w("\t\t%s /* Widget.appex in Embed Foundation Extensions */ = {isa = PBXBuildFile; fileRef = %s /* VibeWidgetExtension.appex */; "
  "settings = {ATTRIBUTES = (RemoveHeadersOnCopy, ); }; };\n" % (EMBED_BF, WID_PROD))
w("/* End PBXBuildFile section */\n")

w("\n/* Begin PBXFileReference section */\n")
for path, (i, name, ftype, tree) in refs.items():
    w("\t\t%s /* %s */ = {isa = PBXFileReference; lastKnownFileType = %s; path = %s; sourceTree = %s; };\n"
      % (i, name, ftype, name, tree))
w("\t\t%s /* VibeWidget.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; "
  "path = VibeWidget.app; sourceTree = BUILT_PRODUCTS_DIR; };\n" % APP_PROD)
w("\t\t%s /* VibeWidgetExtension.appex */ = {isa = PBXFileReference; explicitFileType = \"wrapper.app-extension\"; "
  "includeInIndex = 0; path = VibeWidgetExtension.appex; sourceTree = BUILT_PRODUCTS_DIR; };\n" % WID_PROD)
w("/* End PBXFileReference section */\n")

def group(gid, name, children, path=None):
    w("\t\t%s /* %s */ = {\n\t\t\tisa = PBXGroup;\n\t\t\tchildren = (\n" % (gid, name))
    for c, cn in children:
        w("\t\t\t\t%s /* %s */,\n" % (c, cn))
    w("\t\t\t);\n")
    if path: w("\t\t\tpath = %s;\n" % path)
    else:    w("\t\t\tname = %s;\n" % name)
    w("\t\t\tsourceTree = \"<group>\";\n\t\t};\n")

w("\n/* Begin PBXFrameworksBuildPhase section */\n")
for pid in (APP_FRM_PH, WID_FRM_PH):
    w("\t\t%s /* Frameworks */ = {\n\t\t\tisa = PBXFrameworksBuildPhase;\n\t\t\tbuildActionMask = 2147483647;\n"
      "\t\t\tfiles = (\n\t\t\t);\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t};\n" % pid)
w("/* End PBXFrameworksBuildPhase section */\n")

w("\n/* Begin PBXGroup section */\n")
group(MAIN_GROUP, "VibeWidget", [(G_SHARED, "Shared"), (G_APP, "App"), (G_WID, "Widget"),
                                 (G_ASSETS, "Assets"), (PROD_GROUP, "Products")])
group(G_SHARED, "Shared", [(refs["Shared/" + f][0], f) for f in SHARED], path="Shared")
group(G_APP, "App", [(refs["App/" + f][0], f) for f in APP_SRC]
                    + [(refs["App/Info.plist"][0], "Info.plist"),
                       (refs["App/AppIcon.icns"][0], "AppIcon.icns")], path="App")
group(G_WID, "Widget", [(refs["Widget/" + f][0], f) for f in WID_SRC] + [(refs["Widget/Info.plist"][0], "Info.plist")], path="Widget")
group(G_ASSETS, "Assets", [(refs["Assets/" + f][0], f) for f in ASSETS + APP_ASSETS], path="Assets")
group(PROD_GROUP, "Products", [(APP_PROD, "VibeWidget.app"), (WID_PROD, "VibeWidgetExtension.appex")])
w("/* End PBXGroup section */\n")

w("\n/* Begin PBXCopyFilesBuildPhase section */\n")
w("\t\t%s /* Embed Foundation Extensions */ = {\n\t\t\tisa = PBXCopyFilesBuildPhase;\n"
  "\t\t\tbuildActionMask = 2147483647;\n\t\t\tdstPath = \"\";\n\t\t\tdstSubfolderSpec = 13;\n"
  "\t\t\tfiles = (\n\t\t\t\t%s /* VibeWidgetExtension.appex in Embed Foundation Extensions */,\n\t\t\t);\n"
  "\t\t\tname = \"Embed Foundation Extensions\";\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t};\n"
  % (APP_EMB_PH, EMBED_BF))
w("/* End PBXCopyFilesBuildPhase section */\n")

w("\n/* Begin PBXResourcesBuildPhase section */\n")
for pid, items in ((APP_RES_PH, app_resources), (WID_RES_PH, wid_resources)):
    w("\t\t%s /* Resources */ = {\n\t\t\tisa = PBXResourcesBuildPhase;\n\t\t\tbuildActionMask = 2147483647;\n"
      "\t\t\tfiles = (\n" % pid)
    for b in items: w("\t\t\t\t%s,\n" % b)
    w("\t\t\t);\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t};\n")
w("/* End PBXResourcesBuildPhase section */\n")

w("\n/* Begin PBXSourcesBuildPhase section */\n")
for pid, items in ((APP_SRC_PH, app_sources), (WID_SRC_PH, wid_sources)):
    w("\t\t%s /* Sources */ = {\n\t\t\tisa = PBXSourcesBuildPhase;\n\t\t\tbuildActionMask = 2147483647;\n\t\t\tfiles = (\n" % pid)
    for b in items: w("\t\t\t\t%s,\n" % b)
    w("\t\t\t);\n\t\t\trunOnlyForDeploymentPostprocessing = 0;\n\t\t};\n")
w("/* End PBXSourcesBuildPhase section */\n")

w("\n/* Begin PBXContainerItemProxy section */\n")
w("\t\t%s = {\n\t\t\tisa = PBXContainerItemProxy;\n\t\t\tcontainerPortal = %s;\n\t\t\tproxyType = 1;\n"
  "\t\t\tremoteGlobalIDString = %s;\n\t\t\tremoteInfo = VibeWidgetExtension;\n\t\t};\n" % (PROXY, PROJ, WID_TGT))
w("/* End PBXContainerItemProxy section */\n")

w("\n/* Begin PBXTargetDependency section */\n")
w("\t\t%s = {\n\t\t\tisa = PBXTargetDependency;\n\t\t\ttarget = %s;\n\t\t\ttargetProxy = %s;\n\t\t};\n" % (DEP, WID_TGT, PROXY))
w("/* End PBXTargetDependency section */\n")

w("\n/* Begin PBXNativeTarget section */\n")
w("\t\t%s /* VibeWidget */ = {\n\t\t\tisa = PBXNativeTarget;\n\t\t\tbuildConfigurationList = %s;\n"
  "\t\t\tbuildPhases = (\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t);\n"
  "\t\t\tbuildRules = (\n\t\t\t);\n\t\t\tdependencies = (\n\t\t\t\t%s,\n\t\t\t);\n"
  "\t\t\tname = VibeWidget;\n\t\t\tproductName = VibeWidget;\n\t\t\tproductReference = %s;\n"
  "\t\t\tproductType = \"com.apple.product-type.application\";\n\t\t};\n"
  % (APP_TGT, CL_APP, APP_SRC_PH, APP_FRM_PH, APP_RES_PH, APP_EMB_PH, DEP, APP_PROD))
w("\t\t%s /* VibeWidgetExtension */ = {\n\t\t\tisa = PBXNativeTarget;\n\t\t\tbuildConfigurationList = %s;\n"
  "\t\t\tbuildPhases = (\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t);\n"
  "\t\t\tbuildRules = (\n\t\t\t);\n\t\t\tdependencies = (\n\t\t\t);\n"
  "\t\t\tname = VibeWidgetExtension;\n\t\t\tproductName = VibeWidgetExtension;\n\t\t\tproductReference = %s;\n"
  "\t\t\tproductType = \"com.apple.product-type.app-extension\";\n\t\t};\n"
  % (WID_TGT, CL_WID, WID_SRC_PH, WID_FRM_PH, WID_RES_PH, WID_PROD))
w("/* End PBXNativeTarget section */\n")

w("\n/* Begin PBXProject section */\n")
w("\t\t%s /* Project object */ = {\n\t\t\tisa = PBXProject;\n\t\t\tattributes = {\n"
  "\t\t\t\tBuildIndependentTargetsInParallel = 1;\n\t\t\t\tLastSwiftUpdateCheck = 2600;\n"
  "\t\t\t\tLastUpgradeCheck = 2600;\n\t\t\t\tTargetAttributes = {\n"
  "\t\t\t\t\t%s = {CreatedOnToolsVersion = 26.0; };\n\t\t\t\t\t%s = {CreatedOnToolsVersion = 26.0; };\n"
  "\t\t\t\t};\n\t\t\t};\n\t\t\tbuildConfigurationList = %s;\n\t\t\tcompatibilityVersion = \"Xcode 14.0\";\n"
  "\t\t\tdevelopmentRegion = en;\n\t\t\thasScannedForEncodings = 0;\n\t\t\tknownRegions = (\n\t\t\t\ten,\n\t\t\t\tBase,\n\t\t\t);\n"
  "\t\t\tmainGroup = %s;\n\t\t\tproductRefGroup = %s;\n\t\t\tprojectDirPath = \"\";\n\t\t\tprojectRoot = \"\";\n"
  "\t\t\ttargets = (\n\t\t\t\t%s,\n\t\t\t\t%s,\n\t\t\t);\n\t\t};\n"
  % (PROJ, APP_TGT, WID_TGT, CL_PROJ, MAIN_GROUP, PROD_GROUP, APP_TGT, WID_TGT))
w("/* End PBXProject section */\n")

COMMON = """\t\t\t\tCLANG_ENABLE_MODULES = YES;
\t\t\t\tCLANG_ENABLE_OBJC_ARC = YES;
\t\t\t\tENABLE_STRICT_OBJC_MSGSEND = YES;
\t\t\t\tGCC_NO_COMMON_BLOCKS = YES;
\t\t\t\tMACOSX_DEPLOYMENT_TARGET = %s;
\t\t\t\tSDKROOT = macosx;
\t\t\t\tSWIFT_VERSION = 5.0;
\t\t\t\tALWAYS_SEARCH_USER_PATHS = NO;
""" % DEPLOY

def proj_cfg(cid, name, extra):
    w("\t\t%s /* %s */ = {\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbuildSettings = {\n%s%s\t\t\t};\n"
      "\t\t\tname = %s;\n\t\t};\n" % (cid, name, COMMON, extra, name))

def tgt_cfg(cid, name, extra):
    w("\t\t%s /* %s */ = {\n\t\t\tisa = XCBuildConfiguration;\n\t\t\tbuildSettings = {\n%s\t\t\t};\n"
      "\t\t\tname = %s;\n\t\t};\n" % (cid, name, extra, name))

# Signed with a real Apple Development identity rather than ad-hoc: macOS will
# not load a widget extension whose entitlements are not backed by a signature.
SIGN = """\t\t\t\tCODE_SIGN_STYLE = Manual;
\t\t\t\tCODE_SIGN_IDENTITY = %s;
\t\t\t\tCODE_SIGNING_REQUIRED = %s;
\t\t\t\tCODE_SIGNING_ALLOWED = YES;
\t\t\t\tPROVISIONING_PROFILE_SPECIFIER = "";
\t\t\t\tDEVELOPMENT_TEAM = %s;
\t\t\t\tENABLE_HARDENED_RUNTIME = NO;
\t\t\t\tSWIFT_EMIT_LOC_STRINGS = YES;
\t\t\t\tCURRENT_PROJECT_VERSION = %s;
\t\t\t\tMARKETING_VERSION = %s;
\t\t\t\tAPP_GROUP_IDENTIFIER = %s;
""" % ('"-"' if UNSIGNED else '"Apple Development"',
       "NO" if UNSIGNED else "YES",
       TEAM or '""', BUILD, VERSION, APP_GROUP)

# The app stays unsandboxed — it reads ~/.codex and spawns /usr/bin/security.
APP_CFG = SIGN + """\t\t\t\tINFOPLIST_FILE = App/Info.plist;
\t\t\t\tCODE_SIGN_ENTITLEMENTS = App/VibeWidget.entitlements;
\t\t\t\tENABLE_APP_SANDBOX = NO;
\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = %s;
\t\t\t\tPRODUCT_NAME = VibeWidget;
\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;
\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (
\t\t\t\t\t"$(inherited)",
\t\t\t\t\t"@executable_path/../Frameworks",
\t\t\t\t);
""" % APP_ID

# The widget must be sandboxed or the widget host refuses to load it.
WID_CFG = SIGN + """\t\t\t\tINFOPLIST_FILE = Widget/Info.plist;
\t\t\t\tCODE_SIGN_ENTITLEMENTS = Widget/VibeWidgetExtension.entitlements;
\t\t\t\tENABLE_APP_SANDBOX = YES;
\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = %s;
\t\t\t\tPRODUCT_NAME = VibeWidgetExtension;
\t\t\t\tSKIP_INSTALL = YES;
\t\t\t\tCOMBINE_HIDPI_IMAGES = YES;
\t\t\t\tLD_RUNPATH_SEARCH_PATHS = (
\t\t\t\t\t"$(inherited)",
\t\t\t\t\t"@executable_path/../Frameworks",
\t\t\t\t\t"@executable_path/../../../../Frameworks",
\t\t\t\t);
""" % WID_ID

w("\n/* Begin XCBuildConfiguration section */\n")
proj_cfg(BC["pd"], "Debug", "\t\t\t\tONLY_ACTIVE_ARCH = YES;\n\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-Onone\";\n"
                            "\t\t\t\tSWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;\n\t\t\t\tGCC_OPTIMIZATION_LEVEL = 0;\n"
                            "\t\t\t\tDEBUG_INFORMATION_FORMAT = dwarf;\n\t\t\t\tENABLE_TESTABILITY = YES;\n")
proj_cfg(BC["pr"], "Release", "\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = \"-O\";\n\t\t\t\tSWIFT_COMPILATION_MODE = wholemodule;\n"
                              "\t\t\t\tDEBUG_INFORMATION_FORMAT = \"dwarf-with-dsym\";\n\t\t\t\tENABLE_NS_ASSERTIONS = NO;\n")
tgt_cfg(BC["ad"], "Debug", APP_CFG)
tgt_cfg(BC["ar"], "Release", APP_CFG)
tgt_cfg(BC["wd"], "Debug", WID_CFG)
tgt_cfg(BC["wr"], "Release", WID_CFG)
w("/* End XCBuildConfiguration section */\n")

w("\n/* Begin XCConfigurationList section */\n")
for cid, d, r, label in ((CL_PROJ, BC["pd"], BC["pr"], "PBXProject"),
                         (CL_APP, BC["ad"], BC["ar"], "VibeWidget"),
                         (CL_WID, BC["wd"], BC["wr"], "VibeWidgetExtension")):
    w("\t\t%s /* Build configuration list for %s */ = {\n\t\t\tisa = XCConfigurationList;\n"
      "\t\t\tbuildConfigurations = (\n\t\t\t\t%s /* Debug */,\n\t\t\t\t%s /* Release */,\n\t\t\t);\n"
      "\t\t\tdefaultConfigurationIsVisible = 0;\n\t\t\tdefaultConfigurationName = Release;\n\t\t};\n"
      % (cid, label, d, r))
w("/* End XCConfigurationList section */\n")

w("\t};\n\trootObject = %s /* Project object */;\n}\n" % PROJ)

os.makedirs("VibeWidget.xcodeproj", exist_ok=True)
open("VibeWidget.xcodeproj/project.pbxproj", "w").write("".join(out))
print("wrote VibeWidget.xcodeproj/project.pbxproj")
